metafy-social/web3-smart-contracts

- contracts/NFT/erc1155.sol
Closes #5 
Added ERC1155 NFT contract
Fixes #[ISSUENO]
> Add ERC1155 token contract

- contracts/Misc/CrowdFunding.sol
> Crowd Funding Smart Contract

- contracts/Misc/Faucet.sol
I have added a faucet smart contract under the Misc folder which shows the implementation of the faucet contract.
Fixes #13 
> added faucet contract file

- contracts/Misc/Vesting_Contract.sol
> Vesting Contract

- README.md
- contracts/Misc/CrowdFunding.sol
Gas optimized the CrowdFunding contract. The changes helped to reduce gas costs by ~50k units.
Added a current time function to check and update the deadline for each registrations accordingly.
Also removed "amountRaised=0"  in constructor as solidity by default initializes uint variables with 0.
@0xVikasRushi  please have a look.
> Gas optimized and currentTime function added

- contracts/Coins/erc20std.sol
- contracts/Voting/Election.sol
- contracts/Voting/README.md
Added Voting Contract (Elections.sol) and it's README.md file  <br />
Fixes #3 
NONE
- [   ✅] My PR follows the style guidelines of this project
- [   ✅ ] I have performed a self-check on my work
- [  ✅ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [  ✅ ] My changes in code generate no new warnings
- [   ✅ ] My changes are breaking another fix/feature of the project
- [   ✅ ] I have added test cases to show that my feature works
- [   ✅ ] I have added relevant screenshots in my PR
> Added Voting Contract

- contracts/Auction/README.md
- contracts/Auction/SimpleAuction.sol
Everyone can send their bids during a bidding period. The bids already include sending money / Ether in order to bind the bidders to their bid. If the highest bid is raised, the previous highest bidder gets their money back. After the end of the bidding period, the contract has to be called manually for the beneficiary to receive their money - contracts cannot activate themselves.<br />
Fixes #38 
Contract parameter (auction time and address of beneficiary )
List of Functions
- [ ✅] My PR follows the style guidelines of this project
- [ ✅] I have performed a self-check on my work
> Added Auction Smart Contract

- contracts/Misc/MultiSigWallet.sol
Added Multiple Signature Wallet, Closes #12
Fixes #[ISSUENO]
> Add Multiple Signature Wallet

- contracts/Misc/TicketingSystem/PriceConverter.sol
- contracts/Misc/TicketingSystem/TicketBooker.sol
git pull, updated dependencies <br />
Fixes #6
> ticketing system

- contracts/Ecommerce/ecommerce.sol
Added an ecommerce contract . <br />
Fixes #27 
> added ecommerce contract

- contracts/Misc/NFTDropRegistration.sol
Added NFT Drop Registration ( Open Edition ) smart contract.
Fixes #33 
No extra dependencies added
There is no improvement to be done in this contract, but we can add more contracts for English Auction, Dutch Auction, and Standard Drops as well in the future.
> Added NFT Drop Registration contract

- contracts/Misc/TaxiService.sol
- contracts/Misc/TicketService.sol
This PR is including a taxi service smart contract having all major facilities.
Fixes #58 
> Taxi service smart contract added

- contracts/Games/CoinFlip.sol
Added a smart contract for a two-player game - CoinFlip
Fixes #44 
No extra dependencies
No improvements will be required
> Added coin-flip game smart contract

- contracts/NFT/erc2981-erc721.sol
Implemented the erc2981 standard in a basic erc721 contract.
Fixes #47 
"@openzeppelin/contracts"
> ERC-2981 contract (NFT with royalty)

- contracts/Misc/RestaurantsManager.sol
This PR includes a smart contract that manages a group of restaurants like their ratings, reviews, bills, etc.
Fixes #59 
> Restaurant manager smart contract added

- contracts/Misc/RestaurantsManager.sol
changed contract name and chairman test address
Fixed issues mentioned on PR #62 which was fixing issue #59 @advaita-saha 
> Changes requested for RestaurantsManager contract

- contracts/Misc/CommitReveal.sol
A minimal implementation of commit reveal pattern in solidity <br />
Fixes  [#79](https://github.com/metafy-social/web3-smart-contracts/issues/79)
> Commit Reveal in solidity

- contracts/PreventSpam/CommentMe.sol
Added a folder called PreventSpam, and inside PreventSpam added a smart contract called CommentMe.sol
Fixes #76 
_
_
> Added smart contract to prevent spammers from doing multiple comments

- contracts/Reentrancy attack/ReentrancyAttack.sol
> Reentrancy attack

- contracts/Messaging/Messaging.sol
A smart contract that allows the user to send me a message through the blockchain.
Fixes #88 
Sending gifs through blockchain
> Add Messaging Web3 Script

- contracts/Supplychain/supplychain.sol
created supply chain smart contract<br />
Fixes #68 
maybe we can add delivery functionality
> created supplychain smart contract

- README.md
- contracts/Escrow/EscrowContract.sol
Added EscrowContract.sol <br />
Fixes #66 
Dispute Handling, Gas Optimisation, Security Improvements
> Escrow Smart Contract 

- contracts/FlashLoan/FlashLoan.sol
- contracts/FlashLoan/requirements.txt
I have added the FlashLoan contract file and the requirements.txt file for FlashLoan contract.
Fixes #95 
> added files for FlashLoan contract

- contracts/Games/Casino.sol
_Created a game which is played in Casinos which is number guessing game._ <br />
Fixes #96
@advaita-saha sir, please let me know if there are any changes to be made.
> Add Casino Game

- contracts/NFT Warranty/README.md
- contracts/NFT Warranty/nft-warranty.sol
- Create `contracts/NFT Warranty/nft-warranty.sol`
- Create `contracts/NFT Warranty/README.md`
Fixes #103
`@openzeppelin/contracts`
The Contract is built upon the ERC721 standard and uses OpenZeppelin implementation of the same.
> Add NFT Warranty

- contracts/Misc/LibraryManagement.sol
Added a smart contract for library management 
Fixes #52 
> Added Library Management smart contract

- contracts/Auction/EnglishAuction.sol
Seller of NFT deploys this contract, participants can bid by depositing ETH greater than the current highest bidder. All bidders can withdraw their bid if it is not the current highest bid. Also the auction lasts for 7 days.
Fixes #101
> English Auction

- contracts/TimeLock/TestCoin.sol
- contracts/TimeLock/TimeLock.sol
Added TimeLock.sol and a TestCoin.sol that mints ERC20 Test tokens to test TimeLock.sol <br />
Fixes #94 
OpenZeppelin ERC20 and IERC20
> Added TimeLock contract + testing erc20 contract

- contracts/Event_organize/event.sol
Fixes #78
This is to solve the black ticket selling problem which happens in major events.
This event organizer will have 2 portals, one in which organizer will be able to log in and the other is where the atendee will be able to register. Again this is a basic implementation of decentralization concept.
> Added contract for event organization

- README.md
- contracts/Salary Payment System/README.md
- contracts/Salary Payment System/SalaryPaymentSystem.sol
> Salary Payment System added

- contracts/Banking/BankingSystem.sol
I have made a Banking System
<br />
Fixes #126 
@advaita-saha 
> BankingSystem.sol

- contracts/Misc/VaccineTracker.sol
Added a smart contract to track vaccine batch from the top distributor to different centers/booths.
Fixes #108 
No dependencies
It can be improved by having multiple stages of distribution. 
> Added vaccine tracker smart contract

- contracts/Auction/DutchAuction.sol
Seller of NFT deploys this contract, participants can bid by depositing ETH greater than the current highest bidder. All bidders can withdraw their bid if it is not the current highest bid. Also the auction lasts for 7 days.
Fixes #115
> Dutch Auction

- contracts/blockDNS/Description.md
- contracts/blockDNS/dns.sol
blockDNS is basic implementation of the Domain Name System server built as a smart contract in solidity for ethereum blockchain. DNS translates domain names into corresponding ip addresses so the browser can load the internet resources.
[My Medium Tutorial](https://antoprince001.medium.com/developing-a-blockchain-based-domain-name-system-dns-with-ethereum-c631d8c67bbd) <br />
Fixes #132 
> Add blockchain based DNS smart contract #132

- contracts/Real_TimeData_Feed/Readme.md
- contracts/Real_TimeData_Feed/RealTime_Data_Feed.sol
I have made an datafeed contract with the help  of the chainlink  gateway which is used to get the  real time data from the internet . 
Fixes #138 
> Added Datafeed of eth/usd  via Chainlink gateway

- contracts/Blog/Blog.sol
A blogging smart contract which allows users to create a blog and post that blog . We can also create new blogs or update previous blogs we can also transfer the ownership of that blog to another person. <br />
Fixes #133 
> Added blog smart contract
